### PR TITLE
More presets

### PR DESCRIPTION
**Pull request by Corshi**
Added more of the smooth variants, deleted the doubled `RING10_3` and added grids (png) for patterns as reference.
I will not bother you with more patterns, as I think those are enough as of basic ones, and people will start adding their own anyway

Thanks for this extension!!

### CODE REVIEW

**Comment by bbc-mc** [comment]
Oh thanks for PR. I'll check that.

btw, how you create these graph images? its cool, and i want it.

**Comment by Corshi** [comment]
Just using spreadsheets 😉
Excel / OnlyOffice / LibreOffice
I was using the middle one (free).

**Comment by bbc-mc** [comment]
Hi Corshi.

I have request to fix some.
Would you add some information on README about added Presets which come from some equation ?

I know only SMOOTHSTEP...
`x*x*(3-2*x)`

For users, knowing the origin of preset values ​​may mean something, and prevent them from confuse.

**Comment by Corshi** [comment]
I added them under `Examples of Sigmoid-like Functions` at the end of Readme. I hope it makes some sense. Basically they ware an edit to regular smoothstep, by making more oscillations. I did those in other to move prioritization of chosen sections of the model.
`*Q` are edits that increase the value of `y`. That give sharp step at the edge of the section `x∊<0,1>`, while making a consistent movement. When `y` goes higher then `1` or lower then `0`, just got vertically reversed back.
`/Q` are edits that decreases the amount of steps for smoothstep to complete. That is making `y` horizontally reverse, making multiple smoothstep amplitudes. Making it blend more easily, but also making more "slowing point".
`Cosine` is very similar to smoothstep, but end results can be a bit worse. I added it as a curiosity alongside `Cubic Hermite`, that makes the steps based on the differences in between positions of `x`.
`Cubic Hermite` I gave is not full. This simplified hermite has first section removed, to contain in with restrains of `x∊<0,1>`.

**Comment by Corshi** [comment]
I renamed old `CUBIC_HERMITE` with `FAKE_` and added the `TRUE` variant. All equations in the readme.
Hermite interpolation is often used in graphical shadings, to blend color tones and bumpmaps.
I'm not sure what the real use of it will be for graphical AI data blending, but there is only one way to find out.

**Comment by bbc-mc** [comment]
Thank you for adding informations !

**Pull request merged**
